Repository fulll/actions, pull requests merged in 2019-08, with the labels that each got.

#74 create deploy button
  .gitignore
  release-button/action.yml
  release-button/lib/deploy_button.js
  release-button/package.json
  release-button/src/deploy_button.ts
  release-button/tsconfig.json
  release-button/yarn.lock
Labels: enhancement

#76 doc: github action v2 examples
  php-cs-fixer/README.md
Labels: doc

#78 dispatch v2 actions according to their types
  javascript/release-button/action.yml
  javascript/release-button/lib/deploy_button.js
  javascript/release-button/package.json
  javascript/release-button/src/deploy_button.ts
  javascript/release-button/tsconfig.json
  javascript/release-button/yarn.lock
Labels: enhancement

#80 create workflow to publish javascript github actions
  .github/branch.workflow
  .github/prod-deploy.workflow
  .github/workflows/publish-release-button.yml
Labels: enhancement

#82 Set output variable with result of deploy button
  javascript/release-button/lib/deploy_button.js
  javascript/release-button/package-lock.json
  javascript/release-button/package.json
  javascript/release-button/src/deploy_button.ts
Labels: enhancement, release-button

#86 Add README.md to release-button
  .github/workflows/publish-release-button.yml
  javascript/release-button/README.md
Labels: enhancement, release-button

#88 Define output in action.yml
  javascript/release-button/README.md
  javascript/release-button/action.yml
Labels: enhancement, release-button

#92 sign update not called
  javascript/release-button/lib/deploy_button.js
  javascript/release-button/src/deploy_button.ts
Labels: bug
